name: ALPS Pie v3.100 Keepalive

on:
  schedule:
    - cron: '0 0 * * *'
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: [ '2.7', '3.6', '3.8' ]
    name: Test with Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@main
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install afh-dl
    - name: Download files
      run: |
        LIST="$(<"./t-alps-release-p0.mp2-V3.100/addresses_and_md5sum.txt")"
        mkdir files && cd files
        while ((${SECONDS_LEFT:=10} > 0)); do
          printf "Please wait %ss ...\n" "${SECONDS_LEFT}"; sleep 1; SECONDS_LEFT=$((SECONDS_LEFT - 1))
        done
        set -xv
        for i in $LIST; do
          afh-dl -l ${i%:*} || true
          rm -rf * 2>/dev/null
          sleep 2s
        done
        sleep 2m
        for j in $LIST; do
          afh-dl -l ${j%:*} || true
          rm -rf * 2>/dev/null
          sleep 2s
        done
        sleep 2m
        for k in $LIST; do
          afh-dl -l ${k%:*} || true
          rm -rf * 2>/dev/null
          sleep 2s
        done
        set +xv
