name: ALPS Pie v3.100 Keepalive

on:
  schedule:
    - cron: '0 */3 * * *'
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ 'ubuntu-18.04', 'ubuntu-20.04' ]
        python-version: [ '2.7', '3.8' ]
    name: Test with Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@main
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install afh-dl
    - name: Download files
      timeout-minutes: 240
      run: |
        LIST="$(<"./t-alps-release-p0.mp2-V3.100/addresses_and_md5sum.txt")"
        mkdir files && cd files
        until [[ "${SECONDS_LEFT:=10}" = 0 ]]; do
          printf "Please wait %ss ...\n" "${SECONDS_LEFT}"
          sleep 0.5
          SECONDS_LEFT=$(echo "${SECONDS_LEFT} - 0.5" | bc)
        done
        unset SECONDS_LEFT
        set -xv
        for i in $LIST; do
          afh-dl -l ${i%:*} || true
          rm -rf * 2>/dev/null
          sleep 2s
        done
