name: ALPS Pie v3.100 Keepalive

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install afh-dl
    - name: Download files
      run: |
        LIST="$(<"./t-alps-release-p0.mp2-V3.100/addresses_and_md5sum.txt")"
        mkdir files && cd files
        for i in $LIST; do
          md=${i#:*}
          until test $(md5sum * | awk '{print $1}') = ${md}; do
            afh-dl -l ${i%:*} || true
          done
          rm -rf -- *tar*
        done
