name: ALPS Pie v3.100 Keepalive

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install afh-dl
    - name: Download files
      run: |
        LIST="$(<"./t-alps-release-p0.mp2-V3.100/addresses_and_md5sum.txt")"
        mkdir files && cd files
        while ((${SECONDS_LEFT:=5} > 0)); do
          printf "Please wait %ss ...\n" "${SECONDS_LEFT}"; sleep 1; SECONDS_LEFT=$((SECONDS_LEFT - 1))
        done
        set -xv
        for i in $LIST; do
          afh-dl -l ${i%:*} || true
          fname=$(ls -- *.tar.*)
          until test "$(md5sum $fname | awk '{print $1}')" -eq "${md}"; do
            afh-dl -l ${i%:*} || true
          done
          rm -rf -- *.tar.*
        done
        set +xv
